=== blue3k/BRServer/Server/Config/ServerConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.TheBraves.com/ServerConfig" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.TheBraves.com/ServerConfig" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Servers">
		<xs:annotation>
			<xs:documentation>Server configuration root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DBInstances" type="DBInstance" maxOccurs="unbounded"/>

				<xs:element name="DBCluster" type="DBCluster"  minOccurs="0" maxOccurs="unbounded"/>

				<xs:element name="ModuleServer" type="GenericServer" minOccurs="0" maxOccurs="unbounded" />

				<xs:element name="GameCluster" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="GameDB" type="DBCluster" minOccurs="0" maxOccurs="1" />
							<xs:element name="GameTransactionLogDB" type="DBCluster"  minOccurs="0" maxOccurs="1"/>

							<!-- Eventually we are going to use DBCluster and ModuleServer only -->
							<xs:element name="ModuleServer" type="GenericServer" minOccurs="0" maxOccurs="unbounded" />

							<xs:element name="Game" type="GenericServer" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Game server entity</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="GameInstance" type="GenericServer" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Game server entity</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Name" type="xs:string" use="optional"/>
						<xs:attribute name="GameID" type="xs:string" default="MyTownHero" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>



	<xs:complexType name="GenericServer">
		<xs:annotation>
			<xs:documentation>Server generic configuration</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="NetPrivate">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="NetSocket"/>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>

			<!-- Actually I want them have maximum one each without order -->
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="ModGamePartyManager" type="ModuleSimple"/>
				<xs:element name="ModMonitoring" type="ModuleSimple"/>
				<xs:element name="ModLogin" type="ModuleLogin"/>
				<xs:element name="ModRanking" type="ModuleRanking"/>
				<xs:element name="ModChatting" type="ModuleChatting"/>
				<xs:element name="ModGame" type="ModuleGame"/>
				<xs:element name="ModRelay" type="ModuleGenericPublic"/>
				<xs:element name="ModStreamCollection" type="ModuleGenericPublic"/>
				<xs:element name="ModGameInstanceManager" type="ModuleGameInstanceManager"/>
				<xs:element name="ModInstanceManager" type="ModuleSimple"/>
				<xs:element name="ModMatching_Game_4" type="ModuleMatching"/>
				<xs:element name="ModMatching_Game_8" type="ModuleMatching"/>
				<xs:element name="ModMatchingQueue_Game_4x1" type="ModuleSimple"/>
				<xs:element name="ModMatchingQueue_Game_4x2" type="ModuleSimple"/>
				<xs:element name="ModMatchingQueue_Game_4x3" type="ModuleSimple"/>
				<xs:element name="ModMatchingQueue_Game_4x1S" type="ModuleSimple"/>
				<xs:element name="ModMatchingQueue_Game_4x1W" type="ModuleSimple"/>
				<xs:element name="ModMatchingQueue_Game_8x1" type="ModuleSimple"/>
				<xs:element name="ModMatchingQueue_Game_8x2" type="ModuleSimple"/>
				<xs:element name="ModMatchingQueue_Game_8x3" type="ModuleSimple"/>
				<xs:element name="ModMatchingQueue_Game_8x4" type="ModuleSimple"/>
				<xs:element name="ModMatchingQueue_Game_8x5" type="ModuleSimple"/>
				<xs:element name="ModMatchingQueue_Game_8x6" type="ModuleSimple"/>
				<xs:element name="ModMatchingQueue_Game_8x7" type="ModuleSimple"/>
				<xs:element name="ModMatchingQueue_Game_8x1S" type="ModuleSimple"/>
				<xs:element name="ModMatchingQueue_Game_8x1W" type="ModuleSimple"/>
				<xs:element name="ModPurchaseValidateGoogle" type="ModulePurchaseValidateGoogle"/>
				<xs:element name="ModPurchaseValidateIOS" type="ModulePurchaseValidateIOS"/>
			</xs:choice>

		</xs:sequence>
		<xs:attribute name="UID" type="xs:unsignedInt" use="required">
			<xs:annotation>
				<xs:documentation>Server UID</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="Name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Server Instance Name</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="Executable" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Server executable</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="WorkerThreadCount" type="xs:unsignedInt" use="required">
			<xs:annotation>
				<xs:documentation>Service Entity Thread count(Worker Thread count)</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="NetIOThreadCount" type="xs:unsignedInt" use="required">
			<xs:annotation>
				<xs:documentation>Thread count for network IO</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>


	<xs:complexType name="PublicNetSocket">
		<xs:attribute name="IPV6" type="xs:string" use="required"/>
		<xs:attribute name="IPV4" type="xs:string" use="required"/>
		<xs:attribute name="ListenIP" type="xs:string" use="required"/>
		<xs:attribute name="Port" type="xs:unsignedInt" use="required"/>
		<xs:attribute name="MaxConnection" type="xs:unsignedInt" default="1000000" use="optional"/>
	</xs:complexType>

	<xs:complexType name="NetSocket">
		<xs:annotation>
			<xs:documentation>Network socket info</xs:documentation>
		</xs:annotation>
		<xs:attribute name="IP" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>IP address</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="Port" type="xs:unsignedInt" use="required">
			<xs:annotation>
				<xs:documentation>Port</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>


	<xs:complexType name="DBInstance">
		<xs:attribute name="InstanceName" type="xs:string" use="required"/>
		<xs:attribute name="ConnectionString" type="xs:string" use="required"/>
		<xs:attribute name="UserID" type="xs:string" use="required"/>
		<xs:attribute name="Password" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="DBClusterInstance">
		<xs:attribute name="DBInstanceName" type="xs:string" use="required"/>
		<xs:attribute name="DBName" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="DBCluster">
		<xs:attribute name="ClusterName" type="xs:string" use="required" />
		<xs:attribute name="ClusterType" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="Normal"/>
					<xs:enumeration value="Sharding"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="DBInstanceName" type="xs:string" use="required"/>
		<xs:attribute name="DBName" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="DBServer">
		<xs:annotation>
			<xs:documentation>DB Server information</xs:documentation>
		</xs:annotation>
		<xs:attribute name="ConnectionString" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>DB connection string</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="UserID" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>DB Connection ID</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="Password" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>DB connection password</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="DBName" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>DB Name to connect</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="WorkerCount" type="xs:unsignedInt" use="required">
			<xs:annotation>
				<xs:documentation>Number of Query Worker</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>


	<xs:complexType name="ModuleSimple">
	</xs:complexType>

	<xs:complexType name="ModuleMatching">
		<xs:complexContent>
			<xs:extension base="ModuleSimple">
				<xs:attribute name="UseBot" type="xs:boolean" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="ModuleLogin">
		<xs:complexContent>
			<xs:extension base="ModuleSimple">
				<xs:sequence>
					<xs:element name="NetPublic" type="PublicNetSocket" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="ModuleRanking">
		<xs:complexContent>
			<xs:extension base="ModuleSimple">
				<xs:sequence>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="ModuleChatting">
		<xs:complexContent>
			<xs:extension base="ModuleSimple">
				<xs:sequence>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<xs:complexType name="ModuleGame">
		<xs:complexContent>
			<xs:extension base="ModuleSimple">
				<xs:sequence>
					<xs:element name="NetPublic" type="PublicNetSocket" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="ModuleGameInstanceManager">
		<xs:complexContent>
			<xs:extension base="ModuleSimple">
				<xs:attribute name="Name" type="xs:string" use="required"/>
				<xs:attribute name="DataTable" type="xs:string" use="optional"/>
				<xs:sequence>
					<xs:element name="NetPublic" type="PublicNetSocket" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="ModulePurchaseValidateGoogle">
		<xs:attribute name="Account" type="xs:string" use="required"/>
		<xs:attribute name="P12KeyFile" type="xs:string" use="required"/>
		<xs:attribute name="AuthScopes" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="ModulePurchaseValidateIOS">
		<xs:attribute name="URL" type="xs:string" use="required"/>
		<xs:attribute name="AltURL" type="xs:string" default="" use="optional"/>
	</xs:complexType>

	<xs:complexType name="ModuleGenericPublic">
		<xs:complexContent>
			<xs:extension base="ModuleSimple">
				<xs:sequence>
					<xs:element name="NetPublic" type="PublicNetSocket" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


</xs:schema>

=== blue3k/BRServer/Server/Config/ServerConfig_MyTownHero.xml
<?xml version="1.0" encoding="UTF-8"?>
<Servers xmlns="http://www.TheBraves.com/ServerConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.TheBraves.com/ServerConfig ServerConfig.xsd">
  <DBInstances InstanceName="account00" ConnectionString="192.168.0.9,21022" UserID="blue3k" Password="111" />
  <DBInstances InstanceName="session00" ConnectionString="192.168.0.9,21022" UserID="blue3k" Password="111" />
  <DBInstances InstanceName="ranking" ConnectionString="192.168.0.9,21022" UserID="blue3k" Password="111" />

  <AccountDB ClusterType="Sharding" DBInstanceName="account00" DBName="dbaccount" />
  <LoginSessionDB ClusterType="Sharding" DBInstanceName="session00" DBName="dbsession00" />
  <RankingDB ClusterType="Sharding" DBInstanceName="ranking" DBName="dbconspiracyranking" />


  <ModuleServer UID="11" Name="BRLoginServer01" WorkerThreadCount="4" NetIOThreadCount="4">
    <NetPrivate IP="192.168.0.6" Port="2011"/>
    <ModLogin>
      <NetPublic IPV4="192.168.0.6" IPV6="192.168.0.6" ListenIP="::" Port="21001" MaxConnection="200000"/>
    </ModLogin>
  </ModuleServer>

  <GameCluster Name="Second Game" GameID="MyTownHero" >

    <ModuleServer UID="220" Name="BRMyTownHeroRanking" WorkerThreadCount="4" NetIOThreadCount="4">
      <NetPrivate IP="192.168.0.6" Port="3011"/>
      <ModRanking />
    </ModuleServer>

  </GameCluster>

	
</Servers>
