=== blue3k/BRServer/Tools/TableBuilder/xsd/levelTable.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="LevelTbl">
		<xs:annotation>
			<xs:documentation>Level up table</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="LevelItem" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="Level" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:int">
									<xs:minInclusive value="1"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="RequiredExpTotal" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:int">
									<xs:minInclusive value="1"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== blue3k/BRServer/Server/Conspiracy/table/levelTable.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<LevelTbl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="levelTable.xsd">
	<LevelItem Level="1" RequiredExpTotal="1000"/>
	<LevelItem Level="2" RequiredExpTotal="2000"/>
	<LevelItem Level="3" RequiredExpTotal="3000"/>
	<LevelItem Level="4" RequiredExpTotal="4000"/>
	<LevelItem Level="5" RequiredExpTotal="5000"/>
	<LevelItem Level="6" RequiredExpTotal="6000"/>
	<LevelItem Level="7" RequiredExpTotal="7000"/>
	<LevelItem Level="8" RequiredExpTotal="8000"/>
	<LevelItem Level="9" RequiredExpTotal="9000"/>
	<LevelItem Level="10" RequiredExpTotal="10000"/>
	<LevelItem Level="11" RequiredExpTotal="11000"/>
	<LevelItem Level="12" RequiredExpTotal="12000"/>
	<LevelItem Level="13" RequiredExpTotal="13000"/>
	<LevelItem Level="14" RequiredExpTotal="14000"/>
	<LevelItem Level="15" RequiredExpTotal="15000"/>
	<LevelItem Level="16" RequiredExpTotal="16000"/>
	<LevelItem Level="17" RequiredExpTotal="17000"/>
	<LevelItem Level="18" RequiredExpTotal="18000"/>
	<LevelItem Level="19" RequiredExpTotal="19000"/>
	<LevelItem Level="20" RequiredExpTotal="20000"/>
	<LevelItem Level="21" RequiredExpTotal="21000"/>
	<LevelItem Level="22" RequiredExpTotal="22000"/>
	<LevelItem Level="23" RequiredExpTotal="23000"/>
	<LevelItem Level="24" RequiredExpTotal="24000"/>
	<LevelItem Level="25" RequiredExpTotal="25000"/>
	<LevelItem Level="26" RequiredExpTotal="26000"/>
	<LevelItem Level="27" RequiredExpTotal="27000"/>
	<LevelItem Level="28" RequiredExpTotal="28000"/>
	<LevelItem Level="29" RequiredExpTotal="29000"/>
	<LevelItem Level="30" RequiredExpTotal="30000"/>
	<LevelItem Level="31" RequiredExpTotal="31000"/>
	<LevelItem Level="32" RequiredExpTotal="32000"/>
	<LevelItem Level="33" RequiredExpTotal="33000"/>
	<LevelItem Level="34" RequiredExpTotal="34000"/>
	<LevelItem Level="35" RequiredExpTotal="35000"/>
	<LevelItem Level="36" RequiredExpTotal="36000"/>
	<LevelItem Level="37" RequiredExpTotal="37000"/>
	<LevelItem Level="38" RequiredExpTotal="38000"/>
	<LevelItem Level="39" RequiredExpTotal="39000"/>
	<LevelItem Level="40" RequiredExpTotal="40000"/>
	<LevelItem Level="41" RequiredExpTotal="41000"/>
	<LevelItem Level="42" RequiredExpTotal="42000"/>
	<LevelItem Level="43" RequiredExpTotal="43000"/>
	<LevelItem Level="44" RequiredExpTotal="44000"/>
	<LevelItem Level="45" RequiredExpTotal="45000"/>
	<LevelItem Level="46" RequiredExpTotal="46000"/>
	<LevelItem Level="47" RequiredExpTotal="47000"/>
	<LevelItem Level="48" RequiredExpTotal="48000"/>
	<LevelItem Level="49" RequiredExpTotal="49000"/>
	<LevelItem Level="50" RequiredExpTotal="50000"/>
	<LevelItem Level="51" RequiredExpTotal="51000"/>
	<LevelItem Level="52" RequiredExpTotal="52000"/>
	<LevelItem Level="53" RequiredExpTotal="53000"/>
	<LevelItem Level="54" RequiredExpTotal="54000"/>
	<LevelItem Level="55" RequiredExpTotal="55000"/>
	<LevelItem Level="56" RequiredExpTotal="56000"/>
	<LevelItem Level="57" RequiredExpTotal="57000"/>
	<LevelItem Level="58" RequiredExpTotal="58000"/>
	<LevelItem Level="59" RequiredExpTotal="59000"/>
	<LevelItem Level="60" RequiredExpTotal="60000"/>
	<LevelItem Level="61" RequiredExpTotal="61000"/>
	<LevelItem Level="62" RequiredExpTotal="62000"/>
	<LevelItem Level="63" RequiredExpTotal="63000"/>
	<LevelItem Level="64" RequiredExpTotal="64000"/>
	<LevelItem Level="65" RequiredExpTotal="65000"/>
	<LevelItem Level="66" RequiredExpTotal="66000"/>
	<LevelItem Level="67" RequiredExpTotal="67000"/>
	<LevelItem Level="68" RequiredExpTotal="68000"/>
	<LevelItem Level="69" RequiredExpTotal="69000"/>
	<LevelItem Level="70" RequiredExpTotal="70000"/>
	<LevelItem Level="71" RequiredExpTotal="71000"/>
	<LevelItem Level="72" RequiredExpTotal="72000"/>
	<LevelItem Level="73" RequiredExpTotal="73000"/>
	<LevelItem Level="74" RequiredExpTotal="74000"/>
	<LevelItem Level="75" RequiredExpTotal="75000"/>
	<LevelItem Level="76" RequiredExpTotal="76000"/>
	<LevelItem Level="77" RequiredExpTotal="77000"/>
	<LevelItem Level="78" RequiredExpTotal="78000"/>
	<LevelItem Level="79" RequiredExpTotal="79000"/>
	<LevelItem Level="80" RequiredExpTotal="80000"/>
	<LevelItem Level="81" RequiredExpTotal="81000"/>
	<LevelItem Level="82" RequiredExpTotal="82000"/>
	<LevelItem Level="83" RequiredExpTotal="83000"/>
	<LevelItem Level="84" RequiredExpTotal="84000"/>
	<LevelItem Level="85" RequiredExpTotal="85000"/>
	<LevelItem Level="86" RequiredExpTotal="86000"/>
	<LevelItem Level="87" RequiredExpTotal="87000"/>
	<LevelItem Level="88" RequiredExpTotal="88000"/>
	<LevelItem Level="89" RequiredExpTotal="89000"/>
	<LevelItem Level="90" RequiredExpTotal="90000"/>
	<LevelItem Level="91" RequiredExpTotal="91000"/>
	<LevelItem Level="92" RequiredExpTotal="92000"/>
	<LevelItem Level="93" RequiredExpTotal="93000"/>
	<LevelItem Level="94" RequiredExpTotal="94000"/>
	<LevelItem Level="95" RequiredExpTotal="95000"/>
	<LevelItem Level="96" RequiredExpTotal="96000"/>
	<LevelItem Level="97" RequiredExpTotal="97000"/>
	<LevelItem Level="98" RequiredExpTotal="98000"/>
	<LevelItem Level="99" RequiredExpTotal="99000"/>
	<LevelItem Level="100" RequiredExpTotal="100000"/>
	<LevelItem Level="101" RequiredExpTotal="101000"/>
	<LevelItem Level="102" RequiredExpTotal="102000"/>
	<LevelItem Level="103" RequiredExpTotal="103000"/>
	<LevelItem Level="104" RequiredExpTotal="104000"/>
	<LevelItem Level="105" RequiredExpTotal="105000"/>
	<LevelItem Level="106" RequiredExpTotal="106000"/>
	<LevelItem Level="107" RequiredExpTotal="107000"/>
	<LevelItem Level="108" RequiredExpTotal="108000"/>
	<LevelItem Level="109" RequiredExpTotal="109000"/>
	<LevelItem Level="110" RequiredExpTotal="110000"/>
	<LevelItem Level="111" RequiredExpTotal="111000"/>
	<LevelItem Level="112" RequiredExpTotal="112000"/>
	<LevelItem Level="113" RequiredExpTotal="113000"/>
	<LevelItem Level="114" RequiredExpTotal="114000"/>
	<LevelItem Level="115" RequiredExpTotal="115000"/>
	<LevelItem Level="116" RequiredExpTotal="116000"/>
	<LevelItem Level="117" RequiredExpTotal="117000"/>
	<LevelItem Level="118" RequiredExpTotal="118000"/>
	<LevelItem Level="119" RequiredExpTotal="119000"/>
	<LevelItem Level="120" RequiredExpTotal="120000"/>
	<LevelItem Level="121" RequiredExpTotal="121000"/>
	<LevelItem Level="122" RequiredExpTotal="122000"/>
	<LevelItem Level="123" RequiredExpTotal="123000"/>
	<LevelItem Level="124" RequiredExpTotal="124000"/>
	<LevelItem Level="125" RequiredExpTotal="125000"/>
	<LevelItem Level="126" RequiredExpTotal="126000"/>
	<LevelItem Level="127" RequiredExpTotal="127000"/>
	<LevelItem Level="128" RequiredExpTotal="128000"/>
	<LevelItem Level="129" RequiredExpTotal="129000"/>
	<LevelItem Level="130" RequiredExpTotal="130000"/>
	<LevelItem Level="131" RequiredExpTotal="131000"/>
	<LevelItem Level="132" RequiredExpTotal="132000"/>
	<LevelItem Level="133" RequiredExpTotal="133000"/>
	<LevelItem Level="134" RequiredExpTotal="134000"/>
	<LevelItem Level="135" RequiredExpTotal="135000"/>
	<LevelItem Level="136" RequiredExpTotal="136000"/>
	<LevelItem Level="137" RequiredExpTotal="137000"/>
	<LevelItem Level="138" RequiredExpTotal="138000"/>
	<LevelItem Level="139" RequiredExpTotal="139000"/>
	<LevelItem Level="140" RequiredExpTotal="140000"/>
	<LevelItem Level="141" RequiredExpTotal="141000"/>
	<LevelItem Level="142" RequiredExpTotal="142000"/>
	<LevelItem Level="143" RequiredExpTotal="143000"/>
	<LevelItem Level="144" RequiredExpTotal="144000"/>
	<LevelItem Level="145" RequiredExpTotal="145000"/>
	<LevelItem Level="146" RequiredExpTotal="146000"/>
	<LevelItem Level="147" RequiredExpTotal="147000"/>
	<LevelItem Level="148" RequiredExpTotal="148000"/>
	<LevelItem Level="149" RequiredExpTotal="149000"/>
	<LevelItem Level="150" RequiredExpTotal="150000"/>
	<LevelItem Level="151" RequiredExpTotal="151000"/>
	<LevelItem Level="152" RequiredExpTotal="152000"/>
	<LevelItem Level="153" RequiredExpTotal="153000"/>
	<LevelItem Level="154" RequiredExpTotal="154000"/>
	<LevelItem Level="155" RequiredExpTotal="155000"/>
	<LevelItem Level="156" RequiredExpTotal="156000"/>
	<LevelItem Level="157" RequiredExpTotal="157000"/>
	<LevelItem Level="158" RequiredExpTotal="158000"/>
	<LevelItem Level="159" RequiredExpTotal="159000"/>
	<LevelItem Level="160" RequiredExpTotal="160000"/>
	<LevelItem Level="161" RequiredExpTotal="161000"/>
	<LevelItem Level="162" RequiredExpTotal="162000"/>
	<LevelItem Level="163" RequiredExpTotal="163000"/>
	<LevelItem Level="164" RequiredExpTotal="164000"/>
	<LevelItem Level="165" RequiredExpTotal="165000"/>
	<LevelItem Level="166" RequiredExpTotal="166000"/>
	<LevelItem Level="167" RequiredExpTotal="167000"/>
	<LevelItem Level="168" RequiredExpTotal="168000"/>
	<LevelItem Level="169" RequiredExpTotal="169000"/>
	<LevelItem Level="170" RequiredExpTotal="170000"/>
	<LevelItem Level="171" RequiredExpTotal="171000"/>
	<LevelItem Level="172" RequiredExpTotal="172000"/>
	<LevelItem Level="173" RequiredExpTotal="173000"/>
	<LevelItem Level="174" RequiredExpTotal="174000"/>
	<LevelItem Level="175" RequiredExpTotal="175000"/>
	<LevelItem Level="176" RequiredExpTotal="176000"/>
	<LevelItem Level="177" RequiredExpTotal="177000"/>
	<LevelItem Level="178" RequiredExpTotal="178000"/>
	<LevelItem Level="179" RequiredExpTotal="179000"/>
	<LevelItem Level="180" RequiredExpTotal="180000"/>
	<LevelItem Level="181" RequiredExpTotal="181000"/>
	<LevelItem Level="182" RequiredExpTotal="182000"/>
	<LevelItem Level="183" RequiredExpTotal="183000"/>
	<LevelItem Level="184" RequiredExpTotal="184000"/>
	<LevelItem Level="185" RequiredExpTotal="185000"/>
	<LevelItem Level="186" RequiredExpTotal="186000"/>
	<LevelItem Level="187" RequiredExpTotal="187000"/>
	<LevelItem Level="188" RequiredExpTotal="188000"/>
	<LevelItem Level="189" RequiredExpTotal="189000"/>
