=== blue3k/BRServer/Tools/TableBuilder/xsd/shopTable.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ShopTbl">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ShopItem" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="ShopItemID" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:int">
									<xs:minInclusive value="1"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="ItemInfo" type="xs:string" use="required"/>
						<xs:attribute name="RequiredCash" type="xs:string" use="required"/>
						<xs:attribute name="RequiredGem" type="xs:int" use="required"/>
						<xs:attribute name="RequiredGameMoney" type="xs:int" use="required"/>
						<xs:attribute name="ItemEffect" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="Gem"/>
									<xs:enumeration value="Stamina"/>
									<xs:enumeration value="FriendSlot"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="Quantity" type="xs:int" use="required"/>
						<xs:attribute name="AndroidItemID" type="xs:string"/>
						<xs:attribute name="iOSItemID" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== blue3k/BRServer/Server/Conspiracy/table/shopTable.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<ShopTbl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="shopTable.xsd">
	<ShopItem ShopItemID="1" ItemInfo="마법석 1개" RequiredCash="1050" RequiredGem="0" RequiredGameMoney="0" ItemEffect="Gem" Quantity="1"/>
	<ShopItem ShopItemID="2" ItemInfo="마법석 6개" RequiredCash="5299" RequiredGem="0" RequiredGameMoney="0" ItemEffect="Gem" Quantity="6"/>
	<ShopItem ShopItemID="3" ItemInfo="마법석 12개" RequiredCash="9999" RequiredGem="0" RequiredGameMoney="0" ItemEffect="Gem" Quantity="12"/>
	<ShopItem ShopItemID="4" ItemInfo="마법석 30개" RequiredCash="24000" RequiredGem="0" RequiredGameMoney="0" ItemEffect="Gem" Quantity="30"/>
	<ShopItem ShopItemID="5" ItemInfo="마법석 60개" RequiredCash="46999" RequiredGem="0" RequiredGameMoney="0" ItemEffect="Gem" Quantity="60"/>
	<ShopItem ShopItemID="6" ItemInfo="마법석 85개" RequiredCash="64000" RequiredGem="0" RequiredGameMoney="0" ItemEffect="Gem" Quantity="85"/>
	<ShopItem ShopItemID="7" ItemInfo="하트 모두충전" RequiredCash="0" RequiredGem="5" RequiredGameMoney="0" ItemEffect="Stamina" Quantity="99999"/>
	<ShopItem ShopItemID="8" ItemInfo="하트 1개 충전" RequiredCash="0" RequiredGem="0" RequiredGameMoney="1000" ItemEffect="Stamina" Quantity="1"/>
	<ShopItem ShopItemID="9" ItemInfo="친구슬롯 5개" RequiredCash="0" RequiredGem="5" RequiredGameMoney="0" ItemEffect="FriendSlot" Quantity="5"/>
	<ShopItem ShopItemID="10" ItemInfo="" RequiredCash="0" RequiredGem="5" RequiredGameMoney="0" ItemEffect="ResetRankNormal" Quantity="0"/>
	<ShopItem ShopItemID="11" ItemInfo="" RequiredCash="0" RequiredGem="5" RequiredGameMoney="0" ItemEffect="NickName" Quantity="0"/>
	<ShopItem ShopItemID="12" ItemInfo="" RequiredCash="0" RequiredGem="5" RequiredGameMoney="0" ItemEffect="ReStart" Quantity="0"/>
</ShopTbl>
