=== blue3k/BRServer/Server/Conspiracy/table/animationEventTable.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="AnimationEventTable">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="AnimationEventItem" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="FileName" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string"/>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="Setting" use="optional">
							<xs:simpleType>
								<xs:restriction base="xs:string"/>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="AnimationName" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string"/>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="Type" use="optional" default="Event">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="Sound"/>
									<xs:enumeration value="Effect"/>
									<xs:enumeration value="Event"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="Event" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string"/>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="Time" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:float"/>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="Raised" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:boolean"/>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="Resource" type="xs:string" use="optional"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== blue3k/BRServer/Server/Conspiracy/table/animationEventTable.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<AnimationEventTable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="AnimationEventTable.xsd">
	<AnimationEventItem FileName="char_shared" Setting="Citizen0" AnimationName="char_death" Type="Event" Event="DeathEnd" Time="1.24444449" Raised="false"/>
	<AnimationEventItem FileName="char_shared" Setting="Citizen1" AnimationName="char_death" Type="Event" Event="DeathEnd" Time="1.24444449" Raised="false"/>
	<AnimationEventItem FileName="char_shared" Setting="Citizen2" AnimationName="char_death" Type="Event" Event="DeathEnd" Time="1.24444449" Raised="false"/>
	<AnimationEventItem FileName="char_shared" Setting="Citizen3" AnimationName="char_death" Type="Event" Event="DeathEnd" Time="1.24444449" Raised="false"/>
	<AnimationEventItem FileName="char_shared" Setting="Citizen4" AnimationName="char_death" Type="Event" Event="DeathEnd" Time="1.24444449" Raised="false"/>
	<AnimationEventItem FileName="char_shared" Setting="Citizen5" AnimationName="char_death" Type="Event" Event="DeathEnd" Time="1.24444449" Raised="false"/>
	<AnimationEventItem FileName="char_shared" Setting="Citizen6" AnimationName="char_death" Type="Event" Event="DeathEnd" Time="1.24444449" Raised="false"/>
	<AnimationEventItem FileName="char_shared" Setting="Citizen7" AnimationName="char_death" Type="Event" Event="DeathEnd" Time="1.24444449" Raised="false"/>
	<AnimationEventItem FileName="char_shared" Setting="Seer" AnimationName="char_death" Type="Event" Event="DeathEnd" Time="1.24444449" Raised="false"/>
</AnimationEventTable>
