=== blue3k/BRServer/Server/Conspiracy/table/clientSetting.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ClienSetting">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="GamePlay">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="FreeDebate">
								<xs:complexType>
									<xs:attribute name="ShowRole" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:float"/>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="Phase" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:float"/>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="Description1" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:float"/>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="Description2" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:float"/>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="NightVote">
								<xs:complexType>
									<xs:attribute name="Phase" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:float"/>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="Description" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:float"/>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="VoteForSuspects">
								<xs:complexType>
									<xs:attribute name="Phase" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:float"/>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="Description" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:float"/>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="Result" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:float"/>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="VoteForHanging">
								<xs:complexType>
									<xs:attribute name="Phase1" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:float"/>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="Description1" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:float"/>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="Phase2" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:float"/>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="Description2" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:float"/>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="Description3" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:float"/>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="DefenceOfSuspects">
								<xs:complexType>
									<xs:attribute name="Phase" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:float"/>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="Description" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:float"/>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="End">
								<xs:complexType>
									<xs:attribute name="Phase" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:float"/>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="Description1" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:float"/>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="Description2" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:float"/>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="Description3" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:float"/>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="Result1" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:float"/>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="Result2" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:float"/>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="Result3" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:float"/>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Time">
					<xs:complexType>
						<xs:attribute name="ShowVote" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:float"/>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="HideVote" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:float"/>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="KillAnimation" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:float"/>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== blue3k/BRServer/Server/Conspiracy/table/clientSetting.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<ClienSetting xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="clientSetting.xsd">
	<GamePlay>
		<FreeDebate ShowRole="3" Phase="3" Description1="3" Description2="3"/>
		<NightVote Phase="3" Description="3"/>
		<VoteForSuspects Phase="3" Result="3" Description="3"/>
		<VoteForHanging Phase1="3" Phase2="3" Description1="3" Description2="3" Description3="3"/>
		<DefenceOfSuspects Phase="3" Description="3"/>
		<End Phase="3" Result1="3" Result2="3" Result3="2" Description1="3" Description2="3" Description3="3"/>
	</GamePlay>
	<Time ShowVote="2" HideVote="5" KillAnimation="2"/>
</ClienSetting>
