=== blue3k/BRServer/Server/Conspiracy/table/gameStateTable.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="gameStateTbl">
		<xs:annotation>
			<xs:documentation>Reward experiment</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="StateItem" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="StateItemID" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="None"/>
									<xs:enumeration value="FreeDebate"/>
									<xs:enumeration value="NightVote"/>
									<xs:enumeration value="MorningDebate"/>
									<xs:enumeration value="VoteForSuspects"/>
									<xs:enumeration value="DefenceOfSuspects"/>
									<xs:enumeration value="VoteForHanging"/>
									<xs:enumeration value="End"/>
									<xs:enumeration value="Hanging"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="BGM" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== blue3k/BRServer/Server/Conspiracy/table/gameStateTable.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<gameStateTbl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gameStateTable.xsd">
	<StateItem StateItemID="FreeDebate" BGM="song_test"/>
	<StateItem StateItemID="NightVote" BGM="song_test"/>
	<StateItem StateItemID="MorningDebate" BGM="song_test"/>
	<StateItem StateItemID="VoteForSuspects" BGM="song_test"/>
	<StateItem StateItemID="DefenceOfSuspects" BGM="song_test"/>
	<StateItem StateItemID="VoteForHanging" BGM="song_test"/>
	<StateItem StateItemID="End" BGM="song_test"/>
	<StateItem StateItemID="Hanging" BGM="song_test"/>
</gameStateTbl>
